default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['PGUSER'] || 'project_user' %>
  password: <%= ENV['PGPASSWORD'] || 'password' %>
  host: <%= ENV['PGHOST'] || 'localhost' %>
  pool: 5

development:
  <<: *default
  database: project_manager_api_development

test:
  <<: *default
  database: project_manager_api_test

production:
  <<: *default
  database: project_manager_api_production
  username: project_manager_api
  password: <%= ENV['PROJECT_MANAGER_API_DATABASE_PASSWORD'] %>
